# Standalone asyncio workflow schedule worker
FROM python:3.12-slim

ARG BUILD_VERSION=

ENV PYTHONUNBUFFERED=1 \
    PIP_ROOT_USER_ACTION=ignore \
    PIP_NO_CACHE_DIR=1 \
    BUILD_VERSION=${BUILD_VERSION}

WORKDIR /app
COPY ./build-artifacts /opt/build/
RUN pip install --only-binary :all: -r /opt/build/requirements-workflow-worker.txt
RUN pip install --no-deps --no-index --find-links /opt/build/ workflow-worker registry-pkgs

CMD ["python", "-m", "workflow_worker.main"]
