from datetime import datetime
from typing import Literal

from beanie import Document
from pydantic import Field


class IAccessRole(Document):
    """
    IAccessRole Model

    Generated from: accessRole.ts
    Schema version: asc0.5.1
    Generated at: 2026-04-02T17:28:14.233377Z
    """

    accessRoleId: str = Field(...)
    name: str = Field(...)
    description: str | None = Field(default=None)
    resourceType: Literal["agent", "project", "file", "promptGroup", "mcpServer", "remoteAgent"] = Field(
        default="agent"
    )
    permBits: float = Field(...)
    tenantId: str | None = Field(default=None)
    createdAt: datetime | None = Field(default=None)  # auto-generated by Beanie
    updatedAt: datetime | None = Field(default=None)  # auto-generated by Beanie

    class Settings:
        """
        Index definitions are intentionally left out to avoid conflicts.
        Consult Mongoose schema definitions in the jarvis-api project for index information.
        Note that you cannot know whether a WRITE operation **is possible** to violate
        a unique index constraint without knowing the index information.
        """

        name = "accessroles"
        keep_nulls = False
        use_state_management = True
