from datetime import datetime
from typing import Literal

from beanie import Document
from pydantic import Field
from pymongo import IndexModel


class IAccessRole(Document):
    """
    IAccessRole Model

    Generated from: accessRole.ts
    Schema version: asc0.5.1
    Generated at: 2026-04-02T17:28:14.233377Z
    """

    accessRoleId: str = Field(...)
    name: str = Field(...)
    description: str | None = Field(default=None)
    resourceType: Literal["agent", "project", "file", "promptGroup", "mcpServer", "remoteAgent"] = Field(
        default="agent"
    )
    permBits: float = Field(...)
    tenantId: str | None = Field(default=None)
    createdAt: datetime | None = Field(default=None)  # auto-generated by Beanie
    updatedAt: datetime | None = Field(default=None)  # auto-generated by Beanie

    class Settings:
        name = "accessroles"
        keep_nulls = False
        use_state_management = True

        indexes = [
            [("accessRoleId", 1)],
            [("tenantId", 1)],
            IndexModel([("accessRoleId", 1), ("tenantId", 1)], unique=True),
        ]
