from datetime import UTC, datetime
from enum import StrEnum

from beanie import Document, PydanticObjectId
from pydantic import Field


class PrincipalModel(StrEnum):
    USER = "User"
    GROUP = "Group"
    ROLE = "Role"


class PrincipalType(StrEnum):
    USER = "user"
    GROUP = "group"
    PUBLIC = "public"
    ROLE = "role"


class ResourceType(StrEnum):
    AGENT = "agent"
    PROMPTGROUP = "promptGroup"
    MCPSERVER = "mcpServer"
    REMOTE_AGENT = "remoteAgent"


class IAclEntry(Document):
    """
    IAclEntry Model

    Generated from: aclEntry.ts
    Schema version: asc0.5.1
    Generated at: 2026-04-02T17:28:14.222560Z
    """

    principalType: PrincipalType = Field(...)
    principalId: PydanticObjectId | str | None = Field(default=None)
    principalModel: PrincipalModel | None = Field(default=None)
    resourceType: ResourceType = Field(...)
    resourceId: PydanticObjectId = Field(...)
    permBits: float | None = Field(default=1)
    roleId: PydanticObjectId | None = Field(default=None)  # references IAccessRole collection
    inheritedFrom: PydanticObjectId | None = Field(default=None)
    grantedBy: PydanticObjectId | None = Field(default=None)  # references IUser collection
    grantedAt: datetime = Field(default_factory=lambda: datetime.now(UTC))
    tenantId: str | None = Field(default=None)
    createdAt: datetime | None = Field(default=None)  # auto-generated by Beanie
    updatedAt: datetime | None = Field(default=None)  # auto-generated by Beanie

    class Settings:
        """
        Index definitions are intentionally left out to avoid conflicts.
        Consult Mongoose schema definitions in the jarvis-api project for index information.
        Note that you cannot know whether a WRITE operation **is possible** to violate
        a unique index constraint without knowing the index information.
        """

        name = "aclentries"
        keep_nulls = False
        use_state_management = True
