from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from beanie import Document, PydanticObjectId
from pydantic import Field
from pymongo import IndexModel


class PrincipalModel(StrEnum):
    USER = "User"
    GROUP = "Group"
    ROLE = "Role"


class PrincipalType(StrEnum):
    USER = "user"
    GROUP = "group"
    PUBLIC = "public"
    ROLE = "role"


class ResourceType(StrEnum):
    AGENT = "agent"
    PROMPTGROUP = "promptGroup"
    MCPSERVER = "mcpServer"
    REMOTE_AGENT = "remoteAgent"


class IAclEntry(Document):
    """
    IAclEntry Model

    Generated from: aclEntry.ts
    Schema version: asc0.5.1
    Generated at: 2026-04-02T17:28:14.222560Z
    """

    principalType: PrincipalType = Field(...)
    principalId: dict[str, Any] | None = Field(default=None)
    principalModel: PrincipalModel | None = Field(default=None)
    resourceType: ResourceType = Field(...)
    resourceId: PydanticObjectId = Field(...)
    permBits: float | None = Field(default=1)
    roleId: PydanticObjectId | None = Field(
        default=None, pattern=r"^[0-9a-fA-F]{24}$"
    )  # references IAccessRole collection
    inheritedFrom: PydanticObjectId | None = Field(default=None, pattern=r"^[0-9a-fA-F]{24}$")
    grantedBy: PydanticObjectId | None = Field(
        default=None, pattern=r"^[0-9a-fA-F]{24}$"
    )  # references IUser collection
    grantedAt: datetime = Field(default_factory=lambda: datetime.now(UTC))
    tenantId: str | None = Field(default=None)
    createdAt: datetime | None = Field(default=None)  # auto-generated by Beanie
    updatedAt: datetime | None = Field(default=None)  # auto-generated by Beanie

    class Settings:
        name = "aclentries"
        keep_nulls = False
        use_state_management = True

        indexes = [
            [("principalId", 1)],
            [("resourceId", 1)],
            IndexModel([("inheritedFrom", 1)], sparse=True),
            [("tenantId", 1)],
            [("principalId", 1), ("principalType", 1), ("resourceType", 1), ("resourceId", 1), ("tenantId", 1)],
            [("resourceId", 1), ("principalType", 1), ("principalId", 1), ("tenantId", 1)],
            [("principalId", 1), ("permBits", 1), ("resourceType", 1), ("tenantId", 1)],
        ]
