from datetime import datetime
from typing import Literal

from beanie import Document
from pydantic import Field
from pymongo import IndexModel


class IGroup(Document):
    """
    IGroup Model

    Generated from: group.ts
    Schema version: asc0.5.1
    Generated at: 2026-04-02T17:28:14.224087Z
    """

    name: str = Field(...)
    description: str | None = Field(default=None)
    email: str | None = Field(default=None)
    avatar: str | None = Field(default=None)
    memberIds: list[str] | None = Field(default=None)
    source: Literal["local", "entra"] | None = Field(default="local")
    tenantId: str | None = Field(default=None)
    createdAt: datetime | None = Field(default=None)  # auto-generated by Beanie
    updatedAt: datetime | None = Field(default=None)  # auto-generated by Beanie

    class Settings:
        name = "groups"
        keep_nulls = False
        use_state_management = True

        indexes = [
            [("name", 1)],
            [("email", 1)],
            [("tenantId", 1)],
            IndexModel(
                [("idOnTheSource", 1), ("source", 1), ("tenantId", 1)],
                unique=True,
                partialFilterExpression={"idOnTheSource": {"$exists": True}},
            ),
            [("memberIds", 1)],
        ]
