from datetime import datetime
from typing import Any

from beanie import Document, PydanticObjectId
from pydantic import Field


class MCPServerDocument(Document):
    """
    MCPServerDocument Model

    Generated from: mcpServer.ts
    Schema version: asc0.5.1
    Generated at: 2026-04-02T17:28:14.219827Z
    """

    serverName: str = Field(...)
    config: dict[str, Any] = Field(...)
    author: PydanticObjectId = Field(...)  # references IUser collection
    tenantId: str | None = Field(default=None)
    createdAt: datetime | None = Field(default=None)  # auto-generated by Beanie
    updatedAt: datetime | None = Field(default=None)  # auto-generated by Beanie

    class Settings:
        """
        Index definitions are intentionally left out to avoid conflicts.
        Consult Mongoose schema definitions in the jarvis-api project for index information.
        Note that you cannot know whether a WRITE operation **is possible** to violate
        a unique index constraint without knowing the index information.
        """

        name = "mcpservers"
        keep_nulls = False
        use_state_management = True
