from datetime import datetime
from typing import Any

from beanie import Document, PydanticObjectId
from pydantic import Field
from pymongo import IndexModel


class MCPServerDocument(Document):
    """
    MCPServerDocument Model

    Generated from: mcpServer.ts
    Schema version: asc0.5.1
    Generated at: 2026-04-02T17:28:14.219827Z
    """

    serverName: str = Field(...)
    config: dict[str, Any] = Field(...)
    author: PydanticObjectId = Field(...)  # references IUser collection
    tenantId: str | None = Field(default=None)
    createdAt: datetime | None = Field(default=None)  # auto-generated by Beanie
    updatedAt: datetime | None = Field(default=None)  # auto-generated by Beanie

    class Settings:
        name = "mcpservers"
        keep_nulls = False
        use_state_management = True

        indexes = [
            [("serverName", 1)],
            [("author", 1)],
            [("tenantId", 1)],
            IndexModel([("serverName", 1), ("tenantId", 1)], unique=True),
            [("updatedAt", -1), ("_id", 1)],
        ]
