from datetime import datetime
from enum import StrEnum
from typing import Any

from beanie import Document
from pydantic import BaseModel, Field


class SystemRoles(StrEnum):
    ADMIN = "ADMIN"
    USER = "USER"


class Personalization(BaseModel):
    """Nested model for Personalization"""

    memories: bool | None = Field(default=True)


class Session(BaseModel):
    """Nested model for Session"""

    refreshToken: str | None = Field(default="")


class BackupCode(BaseModel):
    """Nested model for BackupCode"""

    codeHash: str = Field(...)
    used: bool | None = Field(default=False)
    usedAt: datetime | None = Field(default=None)


class IUser(Document):
    """
    IUser Model

    Generated from: user.ts
    Schema version: asc0.5.1
    Generated at: 2026-04-02T17:28:14.214820Z
    """

    name: str | None = Field(default=None)
    username: str | None = Field(default="")
    email: str = Field(..., pattern=r"\S+@\S+\.\S+")
    emailVerified: bool = Field(default=False)
    password: str | None = Field(default=None, min_length=8, max_length=128)
    avatar: str | None = Field(default=None)
    provider: str = Field(default="local")
    role: str | None = Field(default="USER")
    googleId: str | None = Field(default=None)
    facebookId: str | None = Field(default=None)
    openidId: str | None = Field(default=None)
    samlId: str | None = Field(default=None)
    ldapId: str | None = Field(default=None)
    githubId: str | None = Field(default=None)
    discordId: str | None = Field(default=None)
    appleId: str | None = Field(default=None)
    plugins: list[Any] | None = Field(default=None)
    twoFactorEnabled: bool | None = Field(default=False)
    totpSecret: str | None = Field(default=None)
    backupCodes: list[BackupCode] | None = Field(default=None)
    pendingTotpSecret: str | None = Field(default=None)
    pendingBackupCodes: list[BackupCode] | None = Field(default=None)  # DB default: undefined
    refreshToken: list[Session] | None = Field(default=None)
    expiresAt: datetime | None = Field(default=None)
    termsAccepted: bool | None = Field(default=False)
    personalization: Personalization | None = Field(default={})
    favorites: list[dict[str, Any]] | None = Field(default=[])
    idOnTheSource: str | None = Field(default=None)
    tenantId: str | None = Field(default=None)
    createdAt: datetime | None = Field(default=None)  # auto-generated by Beanie
    updatedAt: datetime | None = Field(default=None)  # auto-generated by Beanie

    class Settings:
        name = "users"
        keep_nulls = False
        use_state_management = True
